Repository susverma/HacktoberFest_2021, pull requests merged in 2021-10, with the labels that each got.

#1 Creats a square pattern
  game.py
  square_pattern.py
Labels: hacktoberfest-accepted

#2 Add euclid gcd.py
  gcd.py
Labels: hacktoberfest-accepted

#3 Hollow Square X Star Pattern in java
  Hollow_Square_X_Star_Pattern
Labels: hacktoberfest-accepted

#4 Program_to_Swap_Cases
  swap_case.py
Labels: hacktoberfest-accepted

#5 Create MergeSort.py
  MergeSort.py
Labels: hacktoberfest-accepted

#7 Uploaded Password_Strength_Checker.py
  Password_Strength_Checker.py
Labels: hacktoberfest-accepted

#9 Pass or Fail of overall.
  PassOrFail.java
Labels: hacktoberfest-accepted

#10 Create infix_to_postfix.py
  infix_to_postfix.py
Labels: hacktoberfest-accepted

#11 Table of program added
  README.md
Labels: hacktoberfest-accepted

#8 Program_to_Swap_Cases
  swap_case.py
Labels: hacktoberfest-accepted

#12 Hand Tracker
  HandTracking.py
Labels: hacktoberfest-accepted

#13 Add files via upload
  Armstrong.py
Labels: hacktoberfest-accepted

#14 Create sqroot.py
  sqroot.py
Labels: hacktoberfest-accepted

#15 median_of_2_li.py
  median_of_2_li.py
Labels: hacktoberfest-accepted

#16 Add files via upload
  search.py
Labels: hacktoberfest-accepted

#17 This is email slicer
  EmailSlicer.py
Labels: hacktoberfest-accepted

#19 Added Codes in C++ & Python
  dijkstra.cpp
  pareto_optimal_vectors_search.py
Labels: hacktoberfest-accepted

#20 Update median_of_2_li.py
  median_of_2_li.py
Labels: hacktoberfest-accepted

#21 minesweeper
  minesweeper.py
Labels: hacktoberfest-accepted

#22 Add files via upload
  twisted fibonacci.py
Labels: hacktoberfest-accepted

#23 Create Guess_the_Num.py
  Guess_the_Num.py
Labels: hacktoberfest-accepted

#24 added a penguine.html file
  penguine.html
Labels: hacktoberfest-accepted

#25 Added CricketBattingGame.py
  CricketBattingGame.py
Labels: hacktoberfest-accepted

#27 Added-binarysearch-python
  README.md
  binarysearch-python.py
Labels: hacktoberfest-accepted

#26 Added heapSort.py
  heapSort.py
  quickSort.py
Labels: hacktoberfest-accepted, Hacktoberfest

#29 Create bubble-sorting.py
  bubble-sorting.py
Labels: hacktoberfest-accepted, Hacktoberfest

#30 Converting Kilometers/hour to Miles/hour
  ConvertKilometrestoMilesPython
Labels: hacktoberfest-accepted, Hacktoberfest

#28 Create combining.py
  combining.py
Labels: hacktoberfest-accepted, Hacktoberfest

#32 Depth First Search
  dfs.py
Labels: hacktoberfest-accepted, Hacktoberfest

#33 Create stone_paper_scissor_game.py
  stone_paper_scissor_game.py
Labels: hacktoberfest-accepted, Hacktoberfest

#36 Add files via upload
  transpose of matrix.py
Labels: Hacktoberfest

#37 ADDED ENCRYPTION DECRYPTION
  Encryption Decryption/ENCRYPT-DECRYPT A MESSAGE.py
Labels: hacktoberfest-accepted, Hacktoberfest

#38 FxedSizeSlidingWindow
  README.md
  fixedsizeslidingwindow.py
Labels: hacktoberfest-accepted, Hacktoberfest

#39 Generate Random Password using Python
  password_generator.py
Labels: hacktoberfest-accepted, Hacktoberfest

#34 EDA of IPL
  EDA of IPL .ipynb
Labels: hacktoberfest-accepted, Hacktoberfest

#68 Create Texttospeech.py
  Texttospeech.py
Labels: hacktoberfest-accepted, Hacktoberfest

#69 Create currency_convertor.py
  currency_convertor.py
Labels: Hacktoberfest

#70 Create camel_converter.py
  camel_converter.py
Labels: Hacktoberfest

#71 Create rockpaperscissor.c
  rockpaperscissor.c
Labels: hacktoberfest-accepted, Hacktoberfest
